### ISSUE TITLE
Android app crashes upon push notification

### ISSUE THREAD

**Issue by dzoech** [dzoech/Nudelsieb#50]
Android app installed from published release, i.e. built with Release configuration, crashes when it receives a notification.
Launching the app itself works fine.

Logs from the generated bug report:

```
08-07 01:10:37.619 1000 3821 3875 I ActivityManager: Start proc 23516:dev.zoechbauer.nudelsieb/u0a382 for broadcast dev.zoechbauer.nudelsieb/com.google.firebase.iid.FirebaseInstanceIdReceiver
08-07 01:10:37.634 10382 23516 23516 E bauer.nudelsie: Not starting debugger since process cannot load the jdwp agent.
08-07 01:10:37.636 1000 3821 3988 I AutomaticBrightnessControllerEx: [MultiALC] lux = 44.0, time = 361608124
08-07 01:10:37.674 10382 23516 23516 I bauer.nudelsie: The ClassLoaderContext is a special shared library.
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: Unable to instantiate appComponentFactory
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk"],nativeLibraryDirectories=[/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/lib/arm64, /data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/vendor/lib64]]
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at android.app.LoadedApk.createAppFactory(LoadedApk.java:232)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:737)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at android.app.LoadedApk.getClassLoader(LoadedApk.java:816)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at android.app.LoadedApk.getResources(LoadedApk.java:1038)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at android.app.ContextImpl.createAppContext(ContextImpl.java:2385)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6038)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at android.app.ActivityThread.access$1100(ActivityThread.java:208)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at android.os.Handler.dispatchMessage(Handler.java:106)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at android.os.Looper.loop(Looper.java:205)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at android.app.ActivityThread.main(ActivityThread.java:6991)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at java.lang.reflect.Method.invoke(Native Method)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-07 01:10:37.687 10382 23516 23516 E LoadedApk: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
08-07 01:10:37.804 10382 23516 23516 W monodroid-gc: GREF GC Threshold: 46080
08-07 01:10:37.929 1000 4668 4668 D UsbHostManagerService: boot not completed yet.
08-07 01:10:37.948 10382 23516 23516 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
08-07 01:10:37.963 10382 23516 23516 I FirebaseInitProvider: FirebaseApp initialization successful
08-07 01:10:37.970 10382 23516 23516 D AndroidRuntime: Shutting down VM
FATAL
EXCEPTION
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: FATAL EXCEPTION: main
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: Process: dev.zoechbauer.nudelsieb, PID: 23516
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk"],nativeLibraryDirectories=[/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/lib/arm64, /data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/vendor/lib64]]
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at android.app.ActivityThread.handleReceiver(ActivityThread.java:3485)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at android.app.ActivityThread.access$1200(ActivityThread.java:208)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1707)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at android.os.Looper.loop(Looper.java:205)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6991)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk"],nativeLibraryDirectories=[/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/lib/arm64, /data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/vendor/lib64]]
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:84)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: at android.app.ActivityThread.handleReceiver(ActivityThread.java:3478)
08-07 01:10:37.971 10382 23516 23516 E AndroidRuntime: ... 8 more
08-07 01:10:37.974 10106 5477 5477 W GCM : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=dev.zoechbauer.nudelsieb (has extras) }
08-07 01:10:37.988 1000 3821 10604 D DisplayManagerService: Display listener for pid 21572 died.
08-07 01:10:38.043 10382 23516 23516 I MonoDroid: UNHANDLED EXCEPTION:
08-07 01:10:38.072 10382 23516 23516 I MonoDroid: Java.Lang.RuntimeException: Unable to instantiate receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk"],nativeLibraryDirectories=[/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/lib/arm64, /data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/vendor/lib64]] ---> Java.Lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk"],nativeLibraryDirectories=[/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/lib/arm64, /data/app/dev.zoechbauer.nu
08-07 01:10:38.072 10382 23516 23516 I MonoDroid: --- End of inner exception stack trace ---
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: --- End of managed Java.Lang.RuntimeException stack trace ---
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: java.lang.RuntimeException: Unable to instantiate receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk"],nativeLibraryDirectories=[/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/lib/arm64, /data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/vendor/lib64]]
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at android.app.ActivityThread.handleReceiver(ActivityThread.java:3485)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at android.app.ActivityThread.access$1200(ActivityThread.java:208)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1707)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at android.os.Handler.dispatchMessage(Handler.java:106)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at android.os.Looper.loop(Looper.java:205)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at android.app.ActivityThread.main(ActivityThread.java:6991)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at java.lang.reflect.Method.invoke(Native Method)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk"],nativeLibraryDirectories=[/data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/lib/arm64, /data/app/dev.zoechbauer.nudelsieb-89s5Bj8MpgOwzRXhoi4-gQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/vendor/lib64]]
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:84)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: at android.app.ActivityThread.handleReceiver(ActivityThread.java:3478)
08-07 01:10:38.073 10382 23516 23516 I MonoDroid: ... 8 more
08-07 01:10:38.073 10382 23516 23516 I MonoDroid:
08-07 01:10:38.082 1000 3821 3873 I ActivityManager: Showing crash dialog for package dev.zoechbauer.nudelsieb u0
```

**Comment by dzoech** [comment]
Could be caused by ProGuard not including the firebase package during build.

https://social.msdn.microsoft.com/Forums/en-US/dfd6893f-3bcd-4c18-bd24-a2355b8859b8/firebase-cloud-messaging-not-working-on-release-mode-fcm?forum=xamarinforms

**Comment by dzoech** [comment]
Solution: https://stackoverflow.com/a/62782337/2549398
